
package com.exlibris.dps;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DepositWebServices", targetNamespace = "http://dps.exlibris.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DepositWebServices {


    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg6
     * @param arg7
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "SubmitDateResult", targetNamespace = "")
    @RequestWrapper(localName = "getDepositActivityBySubmitDate", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.GetDepositActivityBySubmitDate")
    @ResponseWrapper(localName = "getDepositActivityBySubmitDateResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.GetDepositActivityBySubmitDateResponse")
    public String getDepositActivityBySubmitDate(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7);

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg6
     * @param arg7
     * @param arg8
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "SubmitDateResultByMF", targetNamespace = "")
    @RequestWrapper(localName = "getDepositActivityBySubmitDateByMaterialFlow", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.GetDepositActivityBySubmitDateByMaterialFlow")
    @ResponseWrapper(localName = "getDepositActivityBySubmitDateByMaterialFlowResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.GetDepositActivityBySubmitDateByMaterialFlowResponse")
    public String getDepositActivityBySubmitDateByMaterialFlow(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        String arg8);

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg6
     * @param arg7
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "UpdateDateResult", targetNamespace = "")
    @RequestWrapper(localName = "getDepositActivityByUpdateDate", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.GetDepositActivityByUpdateDate")
    @ResponseWrapper(localName = "getDepositActivityByUpdateDateResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.GetDepositActivityByUpdateDateResponse")
    public String getDepositActivityByUpdateDate(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7);

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg6
     * @param arg7
     * @param arg8
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "UpdateDateResultByMF", targetNamespace = "")
    @RequestWrapper(localName = "getDepositActivityByUpdateDateByMaterialFlow", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.GetDepositActivityByUpdateDateByMaterialFlow")
    @ResponseWrapper(localName = "getDepositActivityByUpdateDateByMaterialFlowResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.GetDepositActivityByUpdateDateByMaterialFlowResponse")
    public String getDepositActivityByUpdateDateByMaterialFlow(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        String arg8);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHeartBit", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.GetHeartBit")
    @ResponseWrapper(localName = "getHeartBitResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.GetHeartBitResponse")
    public String getHeartBit();

    /**
     * 
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "DepositResult", targetNamespace = "")
    @RequestWrapper(localName = "submitDepositActivity", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.SubmitDepositActivity")
    @ResponseWrapper(localName = "submitDepositActivityResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.SubmitDepositActivityResponse")
    public String submitDepositActivity(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

}
