
package com.exlibris.dps;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SipWebServices", targetNamespace = "http://dps.exlibris.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SipWebServices {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHeartBit", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.GetHeartBit")
    @ResponseWrapper(localName = "getHeartBitResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.GetHeartBitResponse")
    public String getHeartBit();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.exlibris.dps.SipStatusInfo
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "SipStatusInfo", targetNamespace = "")
    @RequestWrapper(localName = "getSIPStatusInfo", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.GetSIPStatusInfo")
    @ResponseWrapper(localName = "getSIPStatusInfoResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.GetSIPStatusInfoResponse")
    public SipStatusInfo getSIPStatusInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSipIEs", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.GetSipIEs")
    @ResponseWrapper(localName = "getSipIEsResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.GetSipIEsResponse")
    public String getSipIEs(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "SipStatusResult", targetNamespace = "")
    @RequestWrapper(localName = "getSipStatus", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.GetSipStatus")
    @ResponseWrapper(localName = "getSipStatusResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.GetSipStatusResponse")
    public String getSipStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
