
package com.exlibris.dps;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DataManagerServicesWS", targetNamespace = "http://dps.exlibris.com/", wsdlLocation = "http://localhost:1801/dpsws/repository/DataManagerServicesWS?wsdl")
public class DataManagerServicesWS_Service
    extends Service
{

    private final static URL DATAMANAGERSERVICESWS_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.exlibris.dps.DataManagerServicesWS_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.exlibris.dps.DataManagerServicesWS_Service.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:1801/dpsws/repository/DataManagerServicesWS?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:1801/dpsws/repository/DataManagerServicesWS?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DATAMANAGERSERVICESWS_WSDL_LOCATION = url;
    }

    public DataManagerServicesWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DataManagerServicesWS_Service() {
        super(DATAMANAGERSERVICESWS_WSDL_LOCATION, new QName("http://dps.exlibris.com/", "DataManagerServicesWS"));
    }

    /**
     * 
     * @return
     *     returns DataManagerServicesWS
     */
    @WebEndpoint(name = "DataManagerServicesWSPort")
    public DataManagerServicesWS getDataManagerServicesWSPort() {
        return super.getPort(new QName("http://dps.exlibris.com/", "DataManagerServicesWSPort"), DataManagerServicesWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DataManagerServicesWS
     */
    @WebEndpoint(name = "DataManagerServicesWSPort")
    public DataManagerServicesWS getDataManagerServicesWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://dps.exlibris.com/", "DataManagerServicesWSPort"), DataManagerServicesWS.class, features);
    }

}
