
package com.exlibris.dps;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 *
 */
@WebFault(name = "UserAuthorizeException", targetNamespace = "http://dps.exlibris.com/")
public class UserAuthorizeException_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     *
     */
    private UserAuthorizeException faultInfo;

    /**
     *
     * @param message
     * @param faultInfo
     */
    public UserAuthorizeException_Exception(String message, UserAuthorizeException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     *
     * @param message
     * @param faultInfo
     * @param cause
     */
    public UserAuthorizeException_Exception(String message, UserAuthorizeException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     *
     * @return
     *     returns fault bean: com.exlibris.dps.UserAuthorizeException
     */
    public UserAuthorizeException getFaultInfo() {
        return faultInfo;
    }

}
