
package com.exlibris.dps;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DepositWebServices", targetNamespace = "http://dps.exlibris.com/", wsdlLocation = "http://localhost:1801/dpsws/deposit/DepositWebServices?wsdl")
public class DepositWebServices_Service
    extends Service
{

    private final static URL DEPOSITWEBSERVICES_WSDL_LOCATION;
    private final static WebServiceException DEPOSITWEBSERVICES_EXCEPTION;
    private final static QName DEPOSITWEBSERVICES_QNAME = new QName("http://dps.exlibris.com/", "DepositWebServices");
    private final static Logger logger = Logger.getLogger(com.exlibris.dps.DepositWebServices_Service.class.getName());

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1801/dpsws/deposit/DepositWebServices?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:1801/dpsws/deposit/DepositWebServices?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DEPOSITWEBSERVICES_WSDL_LOCATION = url;
        DEPOSITWEBSERVICES_EXCEPTION = e;
    }

    public DepositWebServices_Service() {
        super(__getWsdlLocation(), DEPOSITWEBSERVICES_QNAME);
    }

    public DepositWebServices_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), DEPOSITWEBSERVICES_QNAME, features);
    }

    public DepositWebServices_Service(URL wsdlLocation) {
        super(wsdlLocation, DEPOSITWEBSERVICES_QNAME);
    }

    public DepositWebServices_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DEPOSITWEBSERVICES_QNAME, features);
    }

    public DepositWebServices_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DepositWebServices_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DepositWebServices
     */
    @WebEndpoint(name = "DepositWebServicesPort")
    public DepositWebServices getDepositWebServicesPort() {
        return super.getPort(new QName("http://dps.exlibris.com/", "DepositWebServicesPort"), DepositWebServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DepositWebServices
     */
    @WebEndpoint(name = "DepositWebServicesPort")
    public DepositWebServices getDepositWebServicesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://dps.exlibris.com/", "DepositWebServicesPort"), DepositWebServices.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DEPOSITWEBSERVICES_EXCEPTION!= null) {
            throw DEPOSITWEBSERVICES_EXCEPTION;
        }
        return DEPOSITWEBSERVICES_WSDL_LOCATION;
    }

}
