
package com.exlibris.dps;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProducerWebServices", targetNamespace = "http://dps.exlibris.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProducerWebServices {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "removeProducerAgent", targetNamespace = "")
    @RequestWrapper(localName = "removeProducerAgent", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.RemoveProducerAgent")
    @ResponseWrapper(localName = "removeProducerAgentResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.RemoveProducerAgentResponse")
    public String removeProducerAgent(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "linkContactToProdcuer", targetNamespace = "")
    @RequestWrapper(localName = "linkContactToProdcuer", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.LinkContactToProdcuer")
    @ResponseWrapper(localName = "linkContactToProdcuerResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.LinkContactToProdcuerResponse")
    public String linkContactToProdcuer(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "materialFlowsResult", targetNamespace = "")
    @RequestWrapper(localName = "getMaterialFlowsOfProducer", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.GetMaterialFlowsOfProducer")
    @ResponseWrapper(localName = "getMaterialFlowsOfProducerResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.GetMaterialFlowsOfProducerResponse")
    public String getMaterialFlowsOfProducer(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "getContact", targetNamespace = "")
    @RequestWrapper(localName = "getContact", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.GetContact")
    @ResponseWrapper(localName = "getContactResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.GetContactResponse")
    public String getContact(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "updateProducerAgent", targetNamespace = "")
    @RequestWrapper(localName = "updateProducerAgent", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.UpdateProducerAgent")
    @ResponseWrapper(localName = "updateProducerAgentResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.UpdateProducerAgentResponse")
    public String updateProducerAgent(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "updateProducer", targetNamespace = "")
    @RequestWrapper(localName = "updateProducer", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.UpdateProducer")
    @ResponseWrapper(localName = "updateProducerResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.UpdateProducerResponse")
    public String updateProducer(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHeartBit", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.GetHeartBit")
    @ResponseWrapper(localName = "getHeartBitResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.GetHeartBitResponse")
    public String getHeartBit();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "isUserExist", targetNamespace = "")
    @RequestWrapper(localName = "isUserExists", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.IsUserExists")
    @ResponseWrapper(localName = "isUserExistsResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.IsUserExistsResponse")
    public String isUserExists(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "unLinkProducerAgentFromProducer", targetNamespace = "")
    @RequestWrapper(localName = "unLinkProducerAgentFromProducer", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.UnLinkProducerAgentFromProducer")
    @ResponseWrapper(localName = "unLinkProducerAgentFromProducerResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.UnLinkProducerAgentFromProducerResponse")
    public String unLinkProducerAgentFromProducer(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "linkProducerAgentToProducer", targetNamespace = "")
    @RequestWrapper(localName = "linkProducerAgentToProducer", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.LinkProducerAgentToProducer")
    @ResponseWrapper(localName = "linkProducerAgentToProducerResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.LinkProducerAgentToProducerResponse")
    public String linkProducerAgentToProducer(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "getProducerAgent", targetNamespace = "")
    @RequestWrapper(localName = "getProducerAgent", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.GetProducerAgent")
    @ResponseWrapper(localName = "getProducerAgentResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.GetProducerAgentResponse")
    public String getProducerAgent(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "unLinkContactFromProducer", targetNamespace = "")
    @RequestWrapper(localName = "unLinkContactFromProducer", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.UnLinkContactFromProducer")
    @ResponseWrapper(localName = "unLinkContactFromProducerResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.UnLinkContactFromProducerResponse")
    public String unLinkContactFromProducer(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "createProducer", targetNamespace = "")
    @RequestWrapper(localName = "createProducer", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.CreateProducer")
    @ResponseWrapper(localName = "createProducerResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.CreateProducerResponse")
    public String createProducer(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "getProducerDetails", targetNamespace = "")
    @RequestWrapper(localName = "getProducerDetails", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.GetProducerDetails")
    @ResponseWrapper(localName = "getProducerDetailsResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.GetProducerDetailsResponse")
    public String getProducerDetails(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "removeContact", targetNamespace = "")
    @RequestWrapper(localName = "removeContact", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.RemoveContact")
    @ResponseWrapper(localName = "removeContactResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.RemoveContactResponse")
    public String removeContact(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "unLinkContactFromProdcuer", targetNamespace = "")
    @RequestWrapper(localName = "unLinkContactFromProdcuer", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.UnLinkContactFromProdcuer")
    @ResponseWrapper(localName = "unLinkContactFromProdcuerResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.UnLinkContactFromProdcuerResponse")
    public String unLinkContactFromProdcuer(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "createProducerAgent", targetNamespace = "")
    @RequestWrapper(localName = "createProducerAgent", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.CreateProducerAgent")
    @ResponseWrapper(localName = "createProducerAgentResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.CreateProducerAgentResponse")
    public String createProducerAgent(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "producersResultWithIns", targetNamespace = "")
    @RequestWrapper(localName = "getProducersOfProducerAgentWithIns", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.GetProducersOfProducerAgentWithIns")
    @ResponseWrapper(localName = "getProducersOfProducerAgentWithInsResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.GetProducersOfProducerAgentWithInsResponse")
    public String getProducersOfProducerAgentWithIns(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "producersResult", targetNamespace = "")
    @RequestWrapper(localName = "getProducersOfProducerAgent", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.GetProducersOfProducerAgent")
    @ResponseWrapper(localName = "getProducersOfProducerAgentResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.GetProducersOfProducerAgentResponse")
    public String getProducersOfProducerAgent(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "linkContactToProducer", targetNamespace = "")
    @RequestWrapper(localName = "linkContactToProducer", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.LinkContactToProducer")
    @ResponseWrapper(localName = "linkContactToProducerResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.LinkContactToProducerResponse")
    public String linkContactToProducer(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "removeProducer", targetNamespace = "")
    @RequestWrapper(localName = "removeProducer", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.RemoveProducer")
    @ResponseWrapper(localName = "removeProducerResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.RemoveProducerResponse")
    public String removeProducer(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "getInternalUserIdByExternalId", targetNamespace = "")
    @RequestWrapper(localName = "getInternalUserIdByExternalId", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.GetInternalUserIdByExternalId")
    @ResponseWrapper(localName = "getInternalUserIdByExternalIdResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.GetInternalUserIdByExternalIdResponse")
    public String getInternalUserIdByExternalId(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "linkProducerAgentToProdcuer", targetNamespace = "")
    @RequestWrapper(localName = "linkProducerAgentToProdcuer", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.LinkProducerAgentToProdcuer")
    @ResponseWrapper(localName = "linkProducerAgentToProdcuerResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.LinkProducerAgentToProdcuerResponse")
    public String linkProducerAgentToProdcuer(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "unLinkProducerAgentFromProdcuer", targetNamespace = "")
    @RequestWrapper(localName = "unLinkProducerAgentFromProdcuer", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.UnLinkProducerAgentFromProdcuer")
    @ResponseWrapper(localName = "unLinkProducerAgentFromProdcuerResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.UnLinkProducerAgentFromProdcuerResponse")
    public String unLinkProducerAgentFromProdcuer(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "updateContact", targetNamespace = "")
    @RequestWrapper(localName = "updateContact", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.UpdateContact")
    @ResponseWrapper(localName = "updateContactResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.UpdateContactResponse")
    public String updateContact(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "createContact", targetNamespace = "")
    @RequestWrapper(localName = "createContact", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.CreateContact")
    @ResponseWrapper(localName = "createContactResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.CreateContactResponse")
    public String createContact(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
