
package com.exlibris.dps;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 *
 */
@WebFault(name = "ProcessException", targetNamespace = "http://dps.exlibris.com/")
public class ProcessException_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     *
     */
    private ProcessException faultInfo;

    /**
     *
     * @param message
     * @param faultInfo
     */
    public ProcessException_Exception(String message, ProcessException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     *
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ProcessException_Exception(String message, ProcessException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     *
     * @return
     *     returns fault bean: com.exlibris.dps.ProcessException
     */
    public ProcessException getFaultInfo() {
        return faultInfo;
    }

}
