
package com.exlibris.dps;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SipWebServices", targetNamespace = "http://dps.exlibris.com/", wsdlLocation = "http://localhost:1801/dpsws/repository/SipWebServices?wsdl")
public class SipWebServices_Service
    extends Service
{

    private final static URL SIPWEBSERVICES_WSDL_LOCATION;
    private final static WebServiceException SIPWEBSERVICES_EXCEPTION;
    private final static QName SIPWEBSERVICES_QNAME = new QName("http://dps.exlibris.com/", "SipWebServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1801/dpsws/repository/SipWebServices?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIPWEBSERVICES_WSDL_LOCATION = url;
        SIPWEBSERVICES_EXCEPTION = e;
    }

    public SipWebServices_Service() {
        super(__getWsdlLocation(), SIPWEBSERVICES_QNAME);
    }

    public SipWebServices_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIPWEBSERVICES_QNAME, features);
    }

    public SipWebServices_Service(URL wsdlLocation) {
        super(wsdlLocation, SIPWEBSERVICES_QNAME);
    }

    public SipWebServices_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIPWEBSERVICES_QNAME, features);
    }

    public SipWebServices_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SipWebServices_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SipWebServices
     */
    @WebEndpoint(name = "SipWebServicesPort")
    public SipWebServices getSipWebServicesPort() {
        return super.getPort(new QName("http://dps.exlibris.com/", "SipWebServicesPort"), SipWebServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SipWebServices
     */
    @WebEndpoint(name = "SipWebServicesPort")
    public SipWebServices getSipWebServicesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://dps.exlibris.com/", "SipWebServicesPort"), SipWebServices.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIPWEBSERVICES_EXCEPTION!= null) {
            throw SIPWEBSERVICES_EXCEPTION;
        }
        return SIPWEBSERVICES_WSDL_LOCATION;
    }

}
