
package com.exlibris.dps;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DataManagerServicesWS", targetNamespace = "http://dps.exlibris.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DataManagerServicesWS {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHeartBit", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.GetHeartBit")
    @ResponseWrapper(localName = "getHeartBitResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.GetHeartBitResponse")
    public String getHeartBit();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.exlibris.dps.ProcessExecutionStatusInfo
     * @throws ProcessException_Exception
     * @throws UserAuthorizeException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProcessExecutionStatus", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.GetProcessExecutionStatus")
    @ResponseWrapper(localName = "getProcessExecutionStatusResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.GetProcessExecutionStatusResponse")
    public ProcessExecutionStatusInfo getProcessExecutionStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        long arg1)
        throws ProcessException_Exception, UserAuthorizeException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns long
     * @throws ProcessException_Exception
     * @throws UserAuthorizeException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "runProcess", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.RunProcess")
    @ResponseWrapper(localName = "runProcessResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.RunProcessResponse")
    public long runProcess(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        long arg1)
        throws ProcessException_Exception, UserAuthorizeException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.exlibris.dps.SetMembersInfo
     * @throws UserAuthorizeException_Exception
     * @throws SetNotValidException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateSetMembers", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.UpdateSetMembers")
    @ResponseWrapper(localName = "updateSetMembersResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.UpdateSetMembersResponse")
    public SetMembersInfo updateSetMembers(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        long arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        List<String> arg2)
        throws SetNotValidException_Exception, UserAuthorizeException_Exception
    ;

}
